version: '3.8'

services:
  backend:
    build: .
    container_name: board-games-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/board_games_db
      - SPRING_DATASOURCE_USERNAME=boardgames
      - SPRING_DATASOURCE_PASSWORD=boardgames
      - SPRING_PROFILES_ACTIVE=prod
      - TELEGRAM_WEBHOOK_PATH=https://aboardgamebot.ru
      - TELEGRAM_BOT_USERNAME=your_bot_username
      - TELEGRAM_BOT_TOKEN=your_bot_token
      - TELEGRAM_WEBAPP_URL=https://aboardgamebot.ru
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    container_name: board-games-db
    environment:
      POSTGRES_DB: board_games_db
      POSTGRES_USER: boardgames
      POSTGRES_PASSWORD: boardgames
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U boardgames -d board_games_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: