version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: board-games-db-dev
    environment:
      POSTGRES_DB: board_games_db
      POSTGRES_USER: boardgames
      POSTGRES_PASSWORD: boardgames
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U boardgames -d board_games_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: board-games-pgadmin-dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data_dev: 